#ifndef YOUTUBEWEBGET_GLOBAL_H
#define YOUTUBEWEBGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YOUTUBEWEBGET_LIB)
 #define YOUTUBEWEBGET_LIB_EXPORT Q_DECL_EXPORT
#else
 #define YOUTUBEWEBGET_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // YOUTUBEWEBGET_GLOBAL_H
